### ISSUE TITLE
Slight typo and one missing -devel

### ISSUE THREAD

**Issue by doug-rosser** [DataDog/go-metro#22]
At https://github.com/DataDog/go-metro#usage the instructions miss the capitalization of Data"D"og.

It says:

`go install github.com/Datadog/go-metro`

When it should say:

`go install github.com/DataDog/go-metro`

Finally, I also had to install "libpcap-devel" on a CentOS7 system in addition to the other packages. The error, for posterity was as follows:

```
$ go install github.com/DataDog/go-metro                                                   
# github.com/google/gopacket/pcap
src/github.com/google/gopacket/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
```

**Comment by djmitche** [comment]
Looks like #23 fixed this.
