### ISSUE TITLE
Avoid having gauges on the same src and dst but different ports overwrite one another

### ISSUE THREAD

**Issue by olivielpeau** [DataDog/go-metro#8]
We can't tag by port for all the ports because that would create too many short-lived contexts.

A good solution would be to implement our own aggregators to compute the average/min/max over all the ports (i.e. like an agent histogram).

Also, we could allow configuring a list of ports on which `go-metro` would tag the metrics by port.

**Comment by tmichelet** [comment]
We could just send the value as a histogram directly?

**Comment by olivielpeau** [comment]
Ha you're right, we could use dogstatsd's histogram (which for reference is the same as the agent checks' histogram), originally we only looked at the metric types provided by statsd.

@truthbk What do you think?

**Comment by djmitche** [comment]
Sounds like this was solved :)
